version: '3.4'

services:
  demo:
    image: demo
    build: .
    environment:
      NODE_ENV: production
    depends_on:
      - "redis"
      - "my-mongodb"
    ports:
      - 3000:3000

  redis:
    image: redis
    restart: always
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    expose:
      - 6379
    
  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./mongodb:/data/db
      - ./mongoconfig:/data/configdb