version: '3.4'

services:
  demo:
    image: demo
    build: .
    environment:
      NODE_ENV: production
    depends_on:
      - "redis"
      - "my-mongodb"
    ports:
      - 3000:3000

  redis:
    image: redis
    restart: always
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    expose:
      - 6379